DROP TABLE IF EXISTS R1;
DROP TABLE IF EXISTS R2;
DROP TABLE IF EXISTS R3;

CREATE TABLE R1 (
    w VARCHAR,
    x VARCHAR
);

CREATE TABLE R2 (
    y VARCHAR,
    z VARCHAR
);

CREATE TABLE R3 (
    u VARCHAR,
    v VARCHAR
);

INSERT INTO R1 VALUES ('a', 'b');
INSERT INTO R2 VALUES ('c', 'd');
INSERT INTO R3 VALUES ('c', 'c');