CREATE TYPE NULL_INTEGER AS (
    version INTEGER,
    value INTEGER
);

CREATE OR REPLACE FUNCTION TO_NULL_INTEGER(v INTEGER) 
RETURNS NULL_INTEGER AS $$
DECLARE rep NULL_INTEGER;
BEGIN
    rep.value = v;
    rep.version = 0;
    RETURN rep;
END;
$$ LANGUAGE plpgsql;

DROP CAST IF EXISTS (INTEGER AS NULL_INTEGER);
CREATE CAST(INTEGER AS NULL_INTEGER) WITH FUNCTION TO_NULL_INTEGER(INTEGER);

ALTER TABLE Eleve
ALTER COLUMN age TYPE NULL_INTEGER 
USING age::NULL_INTEGER;